trigger:
  branches: { include: [ main ] }

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: Build & Package
  jobs:
  - job: Build
    steps:
    - task: UseDotNet@2
      inputs: { packageType: 'sdk', version: '8.x' }

    - task: DotNetCoreCLI@2
      displayName: Restore
      inputs: { command: 'restore', projects: '**/*.csproj' }

    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'

    - task: DotNetCoreCLI@2
      displayName: Publish (zip)
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: true

    - publish: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Deploy
  displayName: Deploy to Azure App Service
  dependsOn: Build
  variables:
    - group: vg-prod   # Library'de az önce oluşturduğun variable group
  jobs:
  - deployment: WebApp
    environment: 'prod'
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
            artifact: drop

          - task: AzureWebApp@1
            displayName: Deploy to azuretasktracker
            inputs:
              azureSubscription: 'AzureTaskTracker-ServiceConnection'  # service connection adı
              appType: 'webApp'
              appName: 'azuretasktracker'
              package: '$(Pipeline.Workspace)/drop/**/*.zip'

# ConnStr'ı pipeline'dan set etmek için aç:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'AzureTaskTracker-ServiceConnection'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az webapp config connection-string set \
                  --resource-group devops-dashboard-rg \
                  --name azuretasktracker \
                  --settings DefaultConnection="$(AZURE_SQL_CONNECTION_STRING)" \
                  --connection-string-type SQLAzure
