<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\\AzureTaskTracker.Domain\\AzureTaskTracker.Domain.csproj" />
    <ProjectReference Include="..\\..\\contracts\\AzureTaskTracker.Contracts\\AzureTaskTracker.Contracts.csproj" />
  </ItemGroup>
</Project>
